# Generated by Django 4.0.4 on 2022-06-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_building_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32)),
                ('url', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20),
        ),
        migrations.AlterField(
            model_name='building',
            name='rotation',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20),
        ),
        migrations.AlterField(
            model_name='building',
            name='scale',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20),
        ),
    ]
