# Generated by Django 4.0.4 on 2022-06-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_charactermodel_alter_building_elevation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermodel',
            name='model',
            field=models.BinaryField(null=True),
        ),
    ]
