# Generated by Django 4.0.4 on 2022-07-11 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_charactermodel_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='building',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='BuildingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_game_id', models.CharField(max_length=64, verbose_name='game_model_id')),
                ('floor', models.IntegerField(verbose_name='floor_number')),
                ('elevation', models.DecimalField(blank=True, null=True, decimal_places=12, max_digits=20)),
                ('scale', models.DecimalField(blank=True, null=True, decimal_places=12, max_digits=20)),
                ('rotation', models.DecimalField(blank=True, null=True, decimal_places=12, max_digits=20)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.building', verbose_name='building_id')),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='building_id',
        ),
        migrations.RemoveField(
            model_name='building',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='building',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='building',
            name='scale',
        ),
    ]
