# Generated by Django 4.0.4 on 2022-07-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_building_unique_together_building_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermodel',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
