# Generated by Django 4.0.4 on 2022-08-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_charactermodel_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('location_x', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('location_y', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('building_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
