# Generated by Django 4.0.4 on 2022-08-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_parcel_building_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactermodel',
            name='model',
        ),
    ]
