# Generated by Django 4.0.4 on 2022-10-13 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_globalgamesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingblock',
            name='building_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', related_query_name='blocks', to='api.building', verbose_name='building_id'),
        ),
    ]
